export default {
    CREATE_TRIP: 'CREATE_LIST',
    DELETE_TRIP: 'DELETE_LIST',
    DELETE_FROM_TRIP: 'DELETE_FROM_TRIP',
    ADD_TO_TRIP: 'ADD_TO_TRIP',
    FETCH_USER_INFO: 'FETCH_USER_INFO',
    SIGN_IN: 'SIGN_IN',
    SIGN_OUT: 'SIGN_OUT'
}