export default {
    CREATE_TRIP: 'CREATE_LIST',
    DELETE_TRIP: 'DELETE_LIST',
    REMOVE_ITEM: 'REMOVE_ITEM',
    ADD_TO_TRIP: 'ADD_TO_TRIP',
    FETCH_USER_INFO: 'FETCH_USER_INFO',
    SIGN_IN: 'SIGN_IN',
    SIGN_OUT: 'SIGN_OUT',
    FETCH_TRIPS: 'FETCH_TRIPS',
    INCREMENT_QUANTITY: 'INCREMENT_QUANTITY',
    DECREMENT_QUANTITY: 'DECREMENT_QUANTITY'
}